### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yuri25** [gaaarfild/0ez#1]
Попобовал на локальном open-server... что то в конце выдало Fatal error: Undefined class constant 'MYSQL_ATTR_MAX_BUFFER_SIZE' in C:\OpenServer\domains\0ez\config\database.php on line 65

**Comment by garf** [comment]
Установлен ли PHP5 PDO?

**Comment by yuri25** [comment]
Процесс composer instal шел нормально, но в конце выдало:
Nothing to install or update
Generating autoload files

> php artisan clear-compiled

Fatal error: Undefined class constant 'MYSQL_ATTR_MAX_BUFFER_SIZE' in C:\OpenServer\domains\0ez\config\database.php on line 65
Script php artisan clear-compiled handling the post-install-cmd event returned with an error

**Comment by yuri25** [comment]
Да в php.ini раскомментировано extension=php_pdo_mysql.dll

Может просто windows 7 не катит.... Жаль на хостинге потестировать не могу, php 5.4 установлен там.

**Comment by garf** [comment]
Просто в config/database.php убери строчку, где указана эта директива.

**Comment by garf** [comment]
65 строчка 'options' => [PDO::MYSQL_ATTR_MAX_BUFFER_SIZE => 106777216],

**Comment by yuri25** [comment]
Получилось! Зашел в админку, создал категорию, написал пост в эту категорию. Единственно если выбрать миниатюру к топику в админке - то она потом на главной публикуется шириной в страницу что то в районе 780 px. А так вообще прикольно. Планируете что то серьезное делать или просто потренироваться?

**Comment by garf** [comment]
Стараться будем делать так, чтобы было удобно и при этом ничего лишнего, но все нужное.

**Comment by yuri25** [comment]
А насчет миниатюры топика на всю ширину страницы это так и задумано?

**Comment by garf** [comment]
Ну да. :)

**Comment by garf** [comment]
Можете посмотреть примеры на сайтах 
http://0ez.ru
http://0qa.ru
http://rleague.ru

**Comment by yuri25** [comment]
Спасибо огромное, я к сожалению слабоват в программировании, но на уровне обычного пользователя всегда очень люблю потестировать что нибудь новое и интересное. Успехов Вам и вашей команде!

**Comment by garf** [comment]
Большое спасибо вам за поддержку.
Будем рады любым отзывам и пожеланиям.
