### ISSUE TITLE
Не работает кнопка поиска по сайту

### ISSUE THREAD

**Issue by yuri25** [gaaarfild/0ez#12]
Не работает поиск при вводе текста в форму и нажатии на кнопку поиска. Если набрать текст в форме и нажать кнопку Enter на клавиатуре - то все работает и идет переход например по адресу http://ptzportal.ru/?q=Remix  
При нажатии кнопки не срабатывает роут или не передается из формы что то куда то:))) Динар посмотри пожалуйста.

**Comment by garf** [comment]
Исправлено. Можно обновиться :)
