### ISSUE TITLE
зачем эта функция

### ISSUE THREAD

**Issue by stuchin** [gaaarfild/0ez#2]
в моделях определена эта функция, странная для меня

public static function i()
    {
        if (null === self::$_instance) {
            self::$_instance = new self();
        }
        return self::$_instance;
    }

если можно ответить , какого ее назначение, я раньше в моделях не видел похожего

**Comment by garf** [comment]
Это паттерн синглтон. Сделал его для того, чтобы использовать нестатические методы модели, которые сам создаю.

**Comment by stuchin** [comment]
например про категории
вызываем в контроллере (у тебя )
Categories::i()->allWithPostsCount(),
не очень как то код выглядит, прямо глаз режет хотя понятно.

а если сделать функцию allWithPostsCount(), статической и тогда вызывать в контроллере

Categories::allWithPostsCount(), мне кажется так по приятней выглядит, или я что не понимаю, где здесь подводные камни могут быть?

**Comment by garf** [comment]
Подводные камни только в том, что методы надо объявлять как статические и использовать self вместо $this. А я хотел бы более унифицированный доступ. Чтобы  я мог и при создании экземпляра и при вытаскивании данных из БД пользоваться этими методами спокойно.
