### ISSUE TITLE
Ошибка при генерации карты сайта в админке

### ISSUE THREAD

**Issue by yuri25** [gaaarfild/0ez#3]
Вручную нажал кнопку Generate sitemap
Whoops, looks like something went wrong.

1/1
FatalErrorException in 878087574a2d53fa139a53f2afc77738 line 6:
syntax error, unexpected '' !!} version="1.0" encoding="' (T_CONSTANT_ENCAPSED_STRING)
in 878087574a2d53fa139a53f2afc77738 line 6

**Comment by yuri25** [comment]
Если поставить галку отправить пинг при публикации топика, то тоже выдает такое:
Whoops, looks like something went wrong.

1/1
FatalErrorException in 712c598b8004f1457c079c5eba351ddc line 1:
syntax error, unexpected '' !!} version="1.0" encoding="' (T_ENCAPSED_AND_WHITESPACE)
in 712c598b8004f1457c079c5eba351ddc line 1

Но может это из за того что на windows 7 и на локальном open-server?  Хотя установка прошла идеально без единой ошибки.

**Comment by garf** [comment]
Попробуйте подтянуть обновление.

**Comment by yuri25** [comment]
Заменил файл resources/views/files/sitemap.blade.php  Ошибка при генерации карты сайта исчезла, Sitemap generation scheduled.  Единственно в самой админке после генерации карты сайта ссылка внизу немного неверная, ведет сюда http://ezblog/root/settings/ezblog/sitemap.xml   А так если открыть http://ezblog/sitemap.xml  то карта нормально отображается.

**Comment by yuri25** [comment]
Неужели забросили?....:(

**Comment by garf** [comment]
Ни в коем случае. Просто отпуск. Скоро со свежими силами. :)

**Comment by garf** [comment]
Исправлено.
