### ISSUE TITLE
Ошибка на главной

### ISSUE THREAD

**Issue by yuri25** [gaaarfild/0ez#5]
Снова я:) Установил, на главной ошибку выдал:
FatalErrorException in C:\OpenServer\domains\0ez\bootstrap\cache\compiled.php line 9781:
Class 'app\Models\Categories' not found

**Comment by garf** [comment]
Наберите в консоли `php artisan clear-compiled`

**Comment by yuri25** [comment]
Блин это мой косяк:) я по привычке в конце набрал php artisan db:seed  
Выполнил php artisan clear-compiled так теперь это выдало 
FatalErrorException in Model.php line 827:
Class 'app\Models\Categories' not found
Наверняка это из за php artisan db:seed     Сейчас заново переустановлю все, извини пожалуйста.

**Comment by garf** [comment]
`db:seed` не должен был вызвать такой ошибки. Посмотри, есть ли файл `app/Models/Categories.php`

**Comment by yuri25** [comment]
Переустановил... теперь при публикации поста выдает такое:
FatalErrorException in C:\OpenServer\domains\0ez\bootstrap\cache\compiled.php line 9829:
Class 'app\Models\Tags' not found
Файлы Categories.php и Tags.php в папке C:\OpenServer\domains\0ez\app\Models  присутствуют.

**Comment by yuri25** [comment]
Также если теперь в админке перейти просто по адресу http://0ez/root/posts то снова такое выдает:
FatalErrorException in C:\OpenServer\domains\0ez\bootstrap\cache\compiled.php line 9781:
Class 'app\Models\Categories' not found

**Comment by yuri25** [comment]
И собственно на главной странице теперь тоже ошибка:
FatalErrorException in C:\OpenServer\domains\0ez\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php line 827:
Class 'app\Models\Categories' not found

php artisan clear-compiled  выполнял - не помогло.

**Comment by garf** [comment]
Попробуйте создать папку `cache` в папке `bootstrap`, и введите команду `php artisan optimize`

**Comment by garf** [comment]
Так же попробуйте просто вручную удалить файл `C:\OpenServer\domains\0ez\bootstrap\cache\compiled.php`

**Comment by yuri25** [comment]
Там уже есть эта папка, в ней два файла .gitignore и services.json  После выполнения php artisan optimize  файл  services.json пропадает, обновляю главную страницу - ошибка прежняя висит 
FatalErrorException in C:\OpenServer\domains\0ez\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php line 827:
Class 'app\Models\Categories' not found

Файл services.json снова появляется в папке C:\OpenServer\domains\0ez\bootstrap\cache
А файла compiled.php в папке нет...

**Comment by yuri25** [comment]
Пока не заморачивайтесь особо, может open-server или windows 7 глючат. Я перешел таки на debian 8 и php 5.6  Через полчаса поставлю на нормальный хост, тогда отпишусь Вам.

**Comment by garf** [comment]
Буду ждать с нетерпением.

**Comment by yuri25** [comment]
Все таки все равно ошибку выдает при публикации топика... может я что то не сделал или не доделал?  Вот такая же ошибка: 
FatalErrorException in /var/www/admin/data/www/mindtv.ru/bootstrap/cache/compiled.php line 9829:
Class 'app\Models\Tags' not found

**Comment by yuri25** [comment]
Может права какие на каталоги нужно выставить? Я вроде выставил 777 на bootstrap/cache/  а также на папку storage и public/uploads  Может еще где то нужно...

**Comment by yuri25** [comment]
Ну и главная тоже не открывается... подскажите может как то можно включить отладочную информацию... Я поставил в .env DEBUGBAR_ENABLED=true  и в /config/app.php 'debug' => env('APP_DEBUG', true),   но этого не достаточно:(

**Comment by yuri25** [comment]
Выполнил php artisan optimize  - теперь на главной 502 Bad Gateway   nginx/1.8.0

**Comment by yuri25** [comment]
Наверное надо было сначала выполнить php artisan clear-compiled... а я ступил...файл compiled.php там был, а теперь его там нет.

**Comment by yuri25** [comment]
Перезапустил apache и Nginx - теперь на главной восстановилась страница с ошибкой. Наверное Nginx просто вырубился.

**Comment by garf** [comment]
Сейчас попробую воспроизвести у себя.

**Comment by garf** [comment]
Ошибку поправил. Она возникла после того, как по коду прошелся StyleCI и испортил неймспейсы. Сейчас все должно быть в порядке.

**Comment by yuri25** [comment]
Отлично, сейчас заново поставлю и продолжу ковырять:)))) Спасибо.

**Comment by yuri25** [comment]
Блин, теперь белый экран почему то... вернее сначала было Internal Server Error, но это как правило из за того что в htacces есть      Options -MultiViews. Обычно я это комментирую так  
 #     Options -MultiViews и все работает. Сейчас что то не пошло... Завтра продолжу.

**Comment by garf** [comment]
Проверьте логи. Что показывает в них.

**Comment by yuri25** [comment]
Логи apache и nginx? Или где то в системе еще пишется? В папке /storage/logs пусто.

**Comment by yuri25** [comment]
Дал права 777 рекурсивно на все папки сайта и он открылся... значит что то с правами... Просто раньше без манипуляций с правами все открывалось. Подскажите пожалуйста по правам на папки (файлы) чтобы полностью не давать всем подряд 777.

**Comment by yuri25** [comment]
Да, еще картинки в демо топиках вида src="/upload/http://lorempixel.com/700/400/?97592" не отображаются...

**Comment by garf** [comment]
Пропишите для всех папок `755` а для всех файлов `644`.
Далее, для папки `storage` - `777`.
Для папки `bootstrap/cache` - `777`.
И не забудьте все файлы сайта присвоить пользователю, от которого запускается ваш вебсервер и PHP-FPM.
`chown -R user:group /your-app-folder`

**Comment by garf** [comment]
Желательно, для каждой ошибки создавать отдельный Issue. Тогда можно будет следить за их исполнением.

**Comment by yuri25** [comment]
О ты вернулся:) Хорошо, сейчас я все проделаю. Насчет настроек Динар подскажи пожалуйста, у меня apache 2.4 + Nginx 1.8.0 и php 5.6   У меня большинство доменов работают на php 5.6 в режиме модуля apache и только некоторые (пара сайтов)  работают на php 5.4 CGI. Раньше у меня на выделенном сервере я давал папке домена пользователя и группу, который был создан в ispmanager например admin:admin а всем остальным папкам и файлам внутри сайта давал www-data:www-data.  Сейчас на VPS я делаю аналогично. Правильно это или нет я не уверен... вроде работает все.

**Comment by garf** [comment]
Если работает - то норм. Главное не 777. :) Но лучше в этом вопросе наверно ответит сисадмин хороший.

**Comment by yuri25** [comment]
Хостеры мутные какие то... когда у них же у меня был выделенный сервер - помогали хорошо... сейчас на VPS тупят по полной... Сам пытаюсь админить и настроить все... не всегда успешно... В логах apache такую хрень постоянно пишет: 
zend_mm_heap corrupted
[Mon Oct 19 20:12:39.802251 2015] [mpm_itk:error] [pid 17371] child died with signal 11
[Mon Oct 19 20:13:26.437967 2015] [mpm_itk:error] [pid 17342] child died with signal 11
[Mon Oct 19 20:13:33.092296 2015] [mpm_itk:error] [pid 17352] child died with signal 11
[Mon Oct 19 20:13:41.654853 2015] [mpm_itk:error] [pid 17308] child died with signal 11
[Mon Oct 19 20:13:47.176977 2015] [mpm_itk:error] [pid 17339] child died with signal 11
[Mon Oct 19 20:14:23.927896 2015] [mpm_itk:error] [pid 17420] child died with signal 11
[Mon Oct 19 20:14:29.555820 2015] [mpm_itk:error] [pid 17334] child died with signal 11
[Mon Oct 19 20:14:35.226496 2015] [mpm_itk:error] [pid 17398] child died with signal 11
[Mon Oct 19 20:14:42.066304 2015] [mpm_itk:error] [pid 17311] child died with signal 11
[Mon Oct 19 20:14:47.900794 2015] [mpm_itk:error] [pid 17469] child died with signal 11
[Mon Oct 19 20:14:54.468674 2015] [mpm_itk:error] [pid 17476] child died with signal 11
[Mon Oct 19 20:15:18.612795 2015] [mpm_prefork:notice] [pid 7572] AH00171: Graceful restart requested, doing restart
[Mon Oct 19 20:15:19.000362 2015] [mpm_prefork:notice] [pid 7572] AH00163: Apache/2.4.10 (Debian) mpm-itk/2.4.7-02 configured -- resuming normal operations
[Mon Oct 19 20:15:19.000410 2015] [core:notice] [pid 7572] AH00094: Command line: '/usr/sbin/apache2'
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted

Они не могут помочь... отвечают типа "тут с ходу ответить сложно"... давайте отключим для начала opcache и memcached  и посмотрим. Я им говорю что тогда сайты вообще будут тупить по полной... короче кривожопые хостеры:)
